- name: Install JDK
  hosts: all
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: 'yes'
        update_cache: 'yes'
        cache_valid_time: 86400
    - name: install JDK 11
      apt:
        name: openjdk-11-jdk
        state: present